name: 'pkgcheck'
description: 'Test your package with {pkgcheck}.'
inputs:
  cache-version:
    description: 'Integer to use as cache version. Increment to use new cache.'
    required: true
    default: 1
    
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - uses: Dockerfile
      id: pkgcheck
    - uses: actions/upload-artifact@v2
      with:
        name: visual-network
        path: "${{ steps.pkgcheck.outputs.visnet_path }}"
    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: "${{ steps.pkgcheck.outputs.results }}"
