name: 'pkgcheck'
description: 'Test your package with {pkgcheck}.'
inputs:
  ref:
    description: 'The ref to checkout and check. Set to empty string to skip checkout.'
    default: '${{ github.ref }}'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      if: ${{ inputs.ref != ''}} 
      uses: actions/checkout@v2
      with:
        ref: '${{ inputs.ref }}'
        fetch-depth: 0
    - uses: docker://ghcr.io/ropensci-review-tools/pkgcheck-action:0.0.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      id: pkgcheck
    - uses: actions/upload-artifact@v2
      with:
        name: visual-network
        path: "${{ steps.pkgcheck.outputs.visnet_path }}"
    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: "${{ steps.pkgcheck.outputs.results }}"
