name: 'pkgcheck'
description: 'Test your package with {pkgcheck}.'
    
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - uses: docker://ghcr.io/assignuser/pkgcheck-base:actual-docker
      id: pkgcheck
    - uses: actions/upload-artifact@v2
      with:
        name: visual-network
        path: "${{ steps.pkgcheck.outputs.visnet_path }}"
    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: "${{ steps.pkgcheck.outputs.results }}"
